/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('wing_request').del()
  await knex('wing_request').insert([
    {
      exercises_id: 4,
      unit_name: '161 ARW',
      tdy_from: 'PHX',
      tdy_to: 'Bucholz Army Airfield, Marshall Islands',
      airfare_type: 'MIL',
      days_qty: 9,
      personnel_qty: 149,
      acft_type: 'KC-135',
      acft_qty: 2,
      lodging_qty_gov: 28,
      lodging_qty_comm: 116,
      lodging_qty_field: 5,
      meals_provided_gov: false,
      meals_provided_comm: false,
      meals_provided_field: true,
    },
    {
      exercises_id: 1,
      unit_name: '161 ARW',
      tdy_from: 'PHX',
      tdy_to: 'Andersen AFB, Guam',
      airfare_type: 'MIL',
      days_qty: 17,
      personnel_qty: 206,
      acft_type: 'KC-135',
      acft_qty: 3,
      lodging_qty_gov: 69,
      lodging_qty_comm: 130,
      lodging_qty_field: 7,
      meals_provided_gov: true,
      meals_provided_comm: true,
      meals_provided_field: true,
    },
    {
      exercises_id: 4,
      unit_name: '134 FS',
      tdy_from: 'BTV',
      tdy_to: 'Likiep Atoll, Marshall Islands',
      airfare_type: 'COMM',
      days_qty: 9,
      personnel_qty: 78,
      acft_type: 'F-35',
      acft_qty: 4,
      lodging_qty_gov: 58,
      lodging_qty_comm: 0,
      lodging_qty_field: 20,
      meals_provided_gov: true,
      meals_provided_comm: false,
      meals_provided_field: true,
    },
    {
      exercises_id: 1,
      unit_name: '134 FS',
      tdy_from: 'BTV',
      tdy_to: 'Antonio B. Won Pat Intl Airport, Guam',
      airfare_type: 'COMM',
      days_qty: 17,
      personnel_qty: 93,
      acft_type: 'F-35',
      acft_qty: 6,
      lodging_qty_gov: 73,
      lodging_qty_comm: 0,
      lodging_qty_field: 20,
      meals_provided_gov: true,
      meals_provided_comm: false,
      meals_provided_field: true,
    },
    ]);
};
